<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType Condition="'$(OS)' == 'Windows_NT'">WinExe</OutputType>
    <OutputType Condition="'$(OS)' != 'Windows_NT'">Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.1.0</Version>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <FileVersion>2.1.0.0</FileVersion>
    <InformationalVersion>2.1.0</InformationalVersion>
    <AssemblyName>Mania Map Analyzer Overlay.Updater</AssemblyName>
    <RootNamespace>ManiaMapAnalyzerOverlay.Updater</RootNamespace>
  </PropertyGroup>
</Project>
