<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType Condition="'$(OS)' == 'Windows_NT'">WinExe</OutputType>
    <OutputType Condition="'$(OS)' != 'Windows_NT'">Exe</OutputType>
    <AssemblyName>Mania Map Analyzer Overlay.Updater</AssemblyName>
    <RootNamespace>ManiaMapAnalyzerOverlay.Updater</RootNamespace>
  </PropertyGroup>
</Project>
